### ISSUE TITLE
Expose missing API endpoints from ZBD API to ZBD Go SDK

### ISSUE THREAD

**Issue by andrerfneves** [zebedeeio/zbd-go#2]
Our Go SDK needs to be refreshed to include new API endpoints that have since been exposed on the HTTP REST side of things. These APIs are very similar and should follow the same code structure currently available. Check out the ZBD NodeJS SDK here for more details. It should expose the same functionality:
- https://node.zbd.dev/
- https://github.com/zebedeeio/zbd-node

**Comment by andrerfneves** [comment]
Hell yes! Thanks @scshiv29-dev for picking this up. Let me know if you have any questions :)

**Comment by andrerfneves** [comment]
Hey @scshiv29-dev let me know if there's anything you need from me.

**Comment by scshiv29-dev** [comment]
> Hey @scshiv29-dev let me know if there's anything you need from me.

Hey @andrerfneves sorry for this late reply but my motherboard died the very next day of me taking this task , I am so sorry but I won't be able to start it and as I am relocating so will take a new mobo once I move. Please feel free to assign this to anyone who takes it sorry for the inconvenience caused by this.

**Comment by onyedikachi-david** [comment]
Hello, @andrerfneves, is the OAuth2 endpoints part of what should be integrated in the SDK? Aside that below are the endpoints are found that are not implemented:

###  Charges endpoints
- /v0/decode-invoice

### Static charges endpoints
- /v0/static-charges (3 endpoints)
- /v0/static-charges/:STATIC_CHARGE_ID
- /v0/static-charges/:STATIC_CHARGE_ID

### Lightning address endpoints
- v0/ln-address/send-payment
- /v0/ln-address/validate/:LIGHTNING_ADDRESS
- /v0/ln-address/fetch-charge

### Keysend endpoints:
- /v0/keysend-payment

### Utils endpoints
- /v0/btcusd
- /v0/is-supported-region/:IP_ADDRESS

### Internal transfer endpoints
- /v0/internal-transfer 

I want to be sure I'm right, and that I can go ahead to attempt it.

**Comment by andrerfneves** [comment]
@onyedikachi-david that sounds correct!

**Comment by onyedikachi-david** [comment]
Alright @andrerfneves /attempt

**Comment by onyedikachi-david** [comment]
@andrerfneves, Hi, I'll need a clientId and secret to run the test, how do I get one?

**Comment by onyedikachi-david** [comment]
Hello, @andrerfneves

**Comment by andrerfneves** [comment]
Merging and awarding this
